version: '3.5'
services:

  node-red:
    build: ./node-red
    image: node-red-patrol
    container_name: node-red-patrol
    volumes:
      - type: volume
        source: node-red-patrol
        target: /data
    ports:
      - "1885:1880"
    restart: on-failure

  socket-server:
    build: ./socket-server
    image: dotnet-socket-server
    container_name: dotnet-socket-server
    ports:
      - "11017:11017"
    restart: on-failure

volumes:
  node-red-patrol:
